import glance.{type Span}
import gleam/set.{type Set}

/// A fully qualified function name: module path + function name.
pub type QualifiedName {
  QualifiedName(module: String, function: String)
}

/// Distinguishes auto-inferred annotations from enforced invariants.
pub type AnnotationKind {
  /// Auto-generated by `assay infer`. Not enforced.
  Effects
  /// Hand-written invariant. Violations break the build.
  Check
}

/// An effect annotation from a .assay sidecar file.
pub type EffectAnnotation {
  EffectAnnotation(kind: AnnotationKind, function: String, effects: Set(String))
}

/// A single line in an .assay file, preserving structure for round-trip rewrites.
pub type AssayLine {
  AnnotationLine(annotation: EffectAnnotation)
  CommentLine(text: String)
  BlankLine
}

/// A complete parsed .assay file, preserving line-level structure.
pub type AssayFile {
  AssayFile(lines: List(AssayLine))
}

/// A resolved call site found in a function body.
pub type ResolvedCall {
  ResolvedCall(name: QualifiedName, span: Span)
}

/// A local (unresolved) call — needs transitive analysis.
pub type LocalCall {
  LocalCall(function: String, span: Span)
}

/// A single effect violation: an annotated function called something
/// that exceeds its declared effect budget.
pub type Violation {
  Violation(
    function: String,
    call: QualifiedName,
    span: Span,
    declared: Set(String),
    actual: Set(String),
  )
}

/// Result of checking one file.
pub type CheckResult {
  CheckResult(file: String, violations: List(Violation))
}
