// Per-package graded configuration, parsed from `gleam.toml`. Each Gleam
// package can declare:
//
// ```toml
// [tools.graded]
// spec_file = "myapp.graded"          # default: "<name>.graded"
// cache_dir = "build/.graded"         # default: "build/.graded"
// targets = ["erlang", "javascript"]  # default: the top-level `target`
// ```
//
// Every field is optional. If `[tools.graded]` is missing entirely, all
// defaults apply. The `name` field at the top of `gleam.toml` provides the
// package name used to derive the default `spec_file`, and the top-level
// `target` field says which target the package is compiled for.

import filepath
import gleam/bool
import gleam/dict.{type Dict}
import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/result
import gleam/set.{type Set}
import gleam/string
import graded/internal/types
import simplifile
import tom

// Configuration
//
// The `GradedConfig` record and how it is obtained: parsed from a
// `gleam.toml` via `read`, or built entirely from defaults when no file
// is available.

// Resolved per-package configuration. Use `read` to load it from a
// `gleam.toml` path; use `defaults_for` to construct one without IO when
// the package name is already known (for tests or in-memory fixtures).
pub type GradedConfig {
  GradedConfig(
    // Package name as declared in `gleam.toml`'s top-level `name` field.
    package_name: String,
    // Path to the package's spec file, relative to the package root.
    // Contains the public-API effects, `check` invariants, `external`
    // hints, and `type` field annotations that ship to consumers.
    spec_file: String,
    // Path to the per-module cache directory, relative to the package
    // root. Contains all-function inferred effects, regenerated by
    // `graded infer`. Should be inside `build/` so it's gitignored.
    cache_dir: String,
    // Package `version` from `gleam.toml`, when present. Used by `graded
    // pack` to locate the default hex tarball (`build/<name>-<version>.tar`)
    // and to verify a tarball's identity; checking and inference never need
    // it, so it stays optional.
    version: Option(String),
    // The targets this package is analysed on, and where they came from.
    //
    // `[tools.graded].targets` first: a package built for more than one target —
    // a library its consumers compile either way — states them there, and every
    // `@external` is read on each, so a declaration covering one target and a
    // Gleam fallback body covering the other are both charged. Otherwise the
    // top-level `target`, which names exactly one. Where neither field names a
    // target, `types.DefaultedTargets`: the compiler's default stands in for the
    // build, and every target stands in wherever a narrower reading could drop
    // an effect a declaration states.
    //
    // A build overriding the field (`gleam build --target javascript` against a
    // `target = "erlang"` package) is not visible here, so a named set is what
    // the package *declares*, not proof of what was built.
    targets: types.PackageTargets,
  )
}

pub type ConfigError {
  // `gleam.toml` could not be read.
  TomlReadError(path: String, cause: simplifile.FileError)
  // `gleam.toml` parsed but `name` field is missing or not a string.
  MissingPackageName(path: String)
  // `gleam.toml` could not be parsed as valid TOML.
  TomlParseError(path: String)
}

// Read configuration for the project at `<directory>/gleam.toml`. Falls
// back to defaults for any field not present in `[tools.graded]`.
pub fn read(gleam_toml_path: String) -> Result(GradedConfig, ConfigError) {
  use content <- result.try(
    simplifile.read(gleam_toml_path)
    |> result.map_error(TomlReadError(gleam_toml_path, _)),
  )
  use toml <- result.try(
    tom.parse(content)
    |> result.replace_error(TomlParseError(gleam_toml_path)),
  )
  use package_name <- result.try(
    tom.get_string(toml, ["name"])
    |> result.replace_error(MissingPackageName(gleam_toml_path)),
  )
  let spec_file = case tom.get_string(toml, ["tools", "graded", "spec_file"]) {
    Ok(value) -> value
    Error(_) -> default_spec_file(package_name)
  }
  let cache_dir = case tom.get_string(toml, ["tools", "graded", "cache_dir"]) {
    Ok(value) -> value
    Error(_) -> default_cache_dir()
  }
  let version = case tom.get_string(toml, ["version"]) {
    Ok(value) -> Some(value)
    Error(_) -> None
  }
  let targets = read_targets(toml)
  Ok(GradedConfig(package_name:, spec_file:, cache_dir:, version:, targets:))
}

// Which targets a parsed `gleam.toml` names, and how.
//
// `[tools.graded].targets` first: the only place a package built for more than
// one target can say so, since the compiler's own `target` names exactly one.
// A field that is there and states no target graded can read names every target:
// it says the package is built for something, and a reading that picked one of
// them would drop the declarations belonging to the others. Only silence in both
// fields is `DefaultedTargets`.
fn read_targets(toml: Dict(String, tom.Toml)) -> types.PackageTargets {
  case declared_targets(toml) {
    Ok(targets) -> types.NamedTargets(targets)
    Error(TargetsUnreadable) -> types.all_targets()
    Error(TargetsAbsent) ->
      case tom.get_string(toml, ["target"]) {
        Ok(name) ->
          case known_target(name) {
            Ok(target) -> types.NamedTargets(set.from_list([target]))
            Error(Nil) -> types.all_targets()
          }
        Error(tom.NotFound(..)) -> types.DefaultedTargets
        // Present and not a string.
        Error(_) -> types.all_targets()
      }
  }
}

// Why a `[tools.graded].targets` list named no set of targets.
type TargetsMiss {
  // No such key, or one holding an empty list — which states no target the way
  // an absent key does, so it cannot narrow a package to no target at all.
  TargetsAbsent
  // A key that is there and graded cannot read whole: not an array, or holding
  // an entry that is not a target it knows.
  TargetsUnreadable
}

// The `[tools.graded].targets` list, when every entry of it names a target
// graded knows.
fn declared_targets(
  toml: Dict(String, tom.Toml),
) -> Result(Set(String), TargetsMiss) {
  use entries <- result.try(
    case tom.get_array(toml, ["tools", "graded", "targets"]) {
      Ok(entries) -> Ok(entries)
      Error(tom.NotFound(..)) -> Error(TargetsAbsent)
      Error(_) -> Error(TargetsUnreadable)
    },
  )
  use names <- result.try(
    list.try_map(entries, fn(entry) {
      case entry {
        tom.String(name) -> known_target(name)
        _ -> Error(Nil)
      }
    })
    |> result.replace_error(TargetsUnreadable),
  )
  case names {
    [] -> Error(TargetsAbsent)
    _ -> Ok(set.from_list(names))
  }
}

// `name`, when it is one of the targets a Gleam package can be built for. The
// one place a target name is recognised, so the `target` field and the
// `[tools.graded].targets` list cannot come to know different vocabularies.
fn known_target(name: String) -> Result(String, Nil) {
  use <- bool.guard(
    when: !set.contains(types.every_target(), name),
    return: Error(Nil),
  )
  Ok(name)
}

// Build a config using all defaults for a known package name. Useful in
// tests where there's no real `gleam.toml` to read.
//
// Every target, under both readings: this stands in for a package with no
// `gleam.toml` at all, where there is no field whose absence the compiler's
// default could stand in for.
pub fn defaults_for(package_name: String) -> GradedConfig {
  GradedConfig(
    package_name:,
    spec_file: default_spec_file(package_name),
    cache_dir: default_cache_dir(),
    version: None,
    targets: types.all_targets(),
  )
}

pub fn default_spec_file(package_name: String) -> String {
  package_name <> ".graded"
}

pub fn default_cache_dir() -> String {
  "build/.graded"
}

// Path resolution
//
// Derive filesystem and module paths from a package's location: where its
// spec file lives, and the dotted module name of a source file.

// Resolve the full path to a package's spec file given its root directory and
// package name. Reads the package's own `[tools.graded].spec_file`, falling
// back to `<package_name>.graded` when the config is missing or unreadable.
// Single source of truth for "where does package X keep its spec file".
pub fn spec_file_for(package_root: String, package_name: String) -> String {
  let spec_file = case read(filepath.join(package_root, "gleam.toml")) {
    Ok(cfg) -> cfg.spec_file
    Error(_) -> default_spec_file(package_name)
  }
  filepath.join(package_root, spec_file)
}

// Compute the dotted module name (as it appears in `import` statements) for a
// `.gleam` file under a given source directory. For example,
// `module_path_for_source("src/app/router.gleam", "src")` returns
// `"app/router"` — the same string `import` statements use, so the project's
// dependency graph can be built by intersecting the two.
pub fn module_path_for_source(
  gleam_path: String,
  source_directory: String,
) -> String {
  let prefix = source_directory <> "/"
  let relative = case string.starts_with(gleam_path, prefix) {
    True -> string.drop_start(gleam_path, string.length(prefix))
    False -> gleam_path
  }
  filepath.strip_extension(relative)
}

// What went wrong reading a `gleam.toml`, as prose. The one renderer, so the
// public error a caller reads and the message the CLI prints cannot fork.
pub fn describe_error(error: ConfigError) -> String {
  case error {
    TomlReadError(path:, cause:) ->
      "could not read " <> path <> ": " <> simplifile.describe_error(cause)
    MissingPackageName(path:) ->
      "no `name` field in " <> path <> ", or it is not a string"
    TomlParseError(path:) -> path <> " is not valid TOML"
  }
}
